### ISSUE TITLE
Set UTF-8 LATIN1 encoding

### ISSUE THREAD

**Issue by GuilhermeFontaniva** [escpos/escpos#9]
How I set th encoding to work on LATIN1 on CP_CP858

I trying to 
```
text = Escpos::Printer.new
text << Escpos::Helpers.set_printer_encoding(Escpos::CP_CP858)
text << Escpos::Helpers.encode(ptr_text, encoding: "CP-858")
```

but I having the error **code converter not found (UTF-8 to CP-858)**

how I use [this](https://github.com/escpos/escpos/blob/master/lib/escpos.rb#L30) code table?

**Comment by svoboda-jan** [comment]
We use `encode` implementation from ruby under the hood, so it supports anything listed in `Encoding.constants`. In your case `CP858` doesn't seem to be there, at least not in my installation.

You could try `CP850` which differs only by one character or `ISO_8859_1`, since code page 858 supports the entire repertoire of it.

Please note that constants for `set_printer_encoding` and `encoding` option for `encode` are different. It is now clarified in the readme.
